options:
  logging: "CLOUD_LOGGING_ONLY"
steps:
  - name: 'bash'
    args: ['-c', 'echo Hello World!']
  - name: 'bash'
    args: ['-c', 'echo Hi Suresh, Welcome to Cloud Build!']
    args: ['-c', 'echo Welcome to GCP!']
